[modules]
autoload=yes

; Preload required core modules
preload => res_pjsip.so
preload => res_pjsip_session.so

; Codecs & Formats
load => codec_ulaw.so
load => codec_alaw.so
load => codec_gsm.so
load => format_wav.so
load => format_pcm.so
load => format_sln.so

; Applications & Resources
load => app_playback.so
load => app_record.so
load => app_dial.so
load => app_echo.so
load => res_agi.so
load => res_rtp_asterisk.so
load => res_pjsip_transport_websocket.so

; Do not load legacy chan_sip
noload => chan_sip.so
